/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageRouteImport } from './routes/$page'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiPublicCardConfigRouteImport } from './routes/api/public/card-config'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicCheckoutStepRouteImport } from './routes/api/public/checkout-step'
import { Route as ApiPublicEventRouteImport } from './routes/api/public/event'
import { Route as ApiPublicHypercashWebhookRouteImport } from './routes/api/public/hypercash-webhook'
import { Route as ApiPublicMetaEventRouteImport } from './routes/api/public/meta-event'
import { Route as ApiPublicOrderRouteImport } from './routes/api/public/order'
import { Route as ApiPublicPixWebhookRouteImport } from './routes/api/public/pix-webhook'
import { Route as ApiPublicRastreioRouteImport } from './routes/api/public/rastreio'
import { Route as ApiPublicSagacepayWebhookRouteImport } from './routes/api/public/sagacepay-webhook'
import { Route as ApiPublicSettingsRouteImport } from './routes/api/public/settings'
import { Route as ApiPublicUpsellRouteImport } from './routes/api/public/upsell'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardConfigRoute = ApiPublicCardConfigRouteImport.update({
  id: '/api/public/card-config',
  path: '/api/public/card-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutStepRoute = ApiPublicCheckoutStepRouteImport.update({
  id: '/api/public/checkout-step',
  path: '/api/public/checkout-step',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventRoute = ApiPublicEventRouteImport.update({
  id: '/api/public/event',
  path: '/api/public/event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHypercashWebhookRoute =
  ApiPublicHypercashWebhookRouteImport.update({
    id: '/api/public/hypercash-webhook',
    path: '/api/public/hypercash-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMetaEventRoute = ApiPublicMetaEventRouteImport.update({
  id: '/api/public/meta-event',
  path: '/api/public/meta-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderRoute = ApiPublicOrderRouteImport.update({
  id: '/api/public/order',
  path: '/api/public/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPixWebhookRoute = ApiPublicPixWebhookRouteImport.update({
  id: '/api/public/pix-webhook',
  path: '/api/public/pix-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRastreioRoute = ApiPublicRastreioRouteImport.update({
  id: '/api/public/rastreio',
  path: '/api/public/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSagacepayWebhookRoute =
  ApiPublicSagacepayWebhookRouteImport.update({
    id: '/api/public/sagacepay-webhook',
    path: '/api/public/sagacepay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSettingsRoute = ApiPublicSettingsRouteImport.update({
  id: '/api/public/settings',
  path: '/api/public/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUpsellRoute = ApiPublicUpsellRouteImport.update({
  id: '/api/public/upsell',
  path: '/api/public/upsell',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/admin': typeof AdminRoute
  '/api/public/card-config': typeof ApiPublicCardConfigRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/checkout-step': typeof ApiPublicCheckoutStepRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/hypercash-webhook': typeof ApiPublicHypercashWebhookRoute
  '/api/public/meta-event': typeof ApiPublicMetaEventRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/rastreio': typeof ApiPublicRastreioRoute
  '/api/public/sagacepay-webhook': typeof ApiPublicSagacepayWebhookRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/upsell': typeof ApiPublicUpsellRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/admin': typeof AdminRoute
  '/api/public/card-config': typeof ApiPublicCardConfigRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/checkout-step': typeof ApiPublicCheckoutStepRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/hypercash-webhook': typeof ApiPublicHypercashWebhookRoute
  '/api/public/meta-event': typeof ApiPublicMetaEventRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/rastreio': typeof ApiPublicRastreioRoute
  '/api/public/sagacepay-webhook': typeof ApiPublicSagacepayWebhookRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/upsell': typeof ApiPublicUpsellRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$page': typeof PageRoute
  '/admin': typeof AdminRoute
  '/api/public/card-config': typeof ApiPublicCardConfigRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/checkout-step': typeof ApiPublicCheckoutStepRoute
  '/api/public/event': typeof ApiPublicEventRoute
  '/api/public/hypercash-webhook': typeof ApiPublicHypercashWebhookRoute
  '/api/public/meta-event': typeof ApiPublicMetaEventRoute
  '/api/public/order': typeof ApiPublicOrderRoute
  '/api/public/pix-webhook': typeof ApiPublicPixWebhookRoute
  '/api/public/rastreio': typeof ApiPublicRastreioRoute
  '/api/public/sagacepay-webhook': typeof ApiPublicSagacepayWebhookRoute
  '/api/public/settings': typeof ApiPublicSettingsRoute
  '/api/public/upsell': typeof ApiPublicUpsellRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$page'
    | '/admin'
    | '/api/public/card-config'
    | '/api/public/checkout'
    | '/api/public/checkout-step'
    | '/api/public/event'
    | '/api/public/hypercash-webhook'
    | '/api/public/meta-event'
    | '/api/public/order'
    | '/api/public/pix-webhook'
    | '/api/public/rastreio'
    | '/api/public/sagacepay-webhook'
    | '/api/public/settings'
    | '/api/public/upsell'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$page'
    | '/admin'
    | '/api/public/card-config'
    | '/api/public/checkout'
    | '/api/public/checkout-step'
    | '/api/public/event'
    | '/api/public/hypercash-webhook'
    | '/api/public/meta-event'
    | '/api/public/order'
    | '/api/public/pix-webhook'
    | '/api/public/rastreio'
    | '/api/public/sagacepay-webhook'
    | '/api/public/settings'
    | '/api/public/upsell'
  id:
    | '__root__'
    | '/'
    | '/$page'
    | '/admin'
    | '/api/public/card-config'
    | '/api/public/checkout'
    | '/api/public/checkout-step'
    | '/api/public/event'
    | '/api/public/hypercash-webhook'
    | '/api/public/meta-event'
    | '/api/public/order'
    | '/api/public/pix-webhook'
    | '/api/public/rastreio'
    | '/api/public/sagacepay-webhook'
    | '/api/public/settings'
    | '/api/public/upsell'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageRoute: typeof PageRoute
  AdminRoute: typeof AdminRoute
  ApiPublicCardConfigRoute: typeof ApiPublicCardConfigRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicCheckoutStepRoute: typeof ApiPublicCheckoutStepRoute
  ApiPublicEventRoute: typeof ApiPublicEventRoute
  ApiPublicHypercashWebhookRoute: typeof ApiPublicHypercashWebhookRoute
  ApiPublicMetaEventRoute: typeof ApiPublicMetaEventRoute
  ApiPublicOrderRoute: typeof ApiPublicOrderRoute
  ApiPublicPixWebhookRoute: typeof ApiPublicPixWebhookRoute
  ApiPublicRastreioRoute: typeof ApiPublicRastreioRoute
  ApiPublicSagacepayWebhookRoute: typeof ApiPublicSagacepayWebhookRoute
  ApiPublicSettingsRoute: typeof ApiPublicSettingsRoute
  ApiPublicUpsellRoute: typeof ApiPublicUpsellRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$page': {
      id: '/$page'
      path: '/$page'
      fullPath: '/$page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card-config': {
      id: '/api/public/card-config'
      path: '/api/public/card-config'
      fullPath: '/api/public/card-config'
      preLoaderRoute: typeof ApiPublicCardConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout-step': {
      id: '/api/public/checkout-step'
      path: '/api/public/checkout-step'
      fullPath: '/api/public/checkout-step'
      preLoaderRoute: typeof ApiPublicCheckoutStepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/event': {
      id: '/api/public/event'
      path: '/api/public/event'
      fullPath: '/api/public/event'
      preLoaderRoute: typeof ApiPublicEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hypercash-webhook': {
      id: '/api/public/hypercash-webhook'
      path: '/api/public/hypercash-webhook'
      fullPath: '/api/public/hypercash-webhook'
      preLoaderRoute: typeof ApiPublicHypercashWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta-event': {
      id: '/api/public/meta-event'
      path: '/api/public/meta-event'
      fullPath: '/api/public/meta-event'
      preLoaderRoute: typeof ApiPublicMetaEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order': {
      id: '/api/public/order'
      path: '/api/public/order'
      fullPath: '/api/public/order'
      preLoaderRoute: typeof ApiPublicOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pix-webhook': {
      id: '/api/public/pix-webhook'
      path: '/api/public/pix-webhook'
      fullPath: '/api/public/pix-webhook'
      preLoaderRoute: typeof ApiPublicPixWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/rastreio': {
      id: '/api/public/rastreio'
      path: '/api/public/rastreio'
      fullPath: '/api/public/rastreio'
      preLoaderRoute: typeof ApiPublicRastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sagacepay-webhook': {
      id: '/api/public/sagacepay-webhook'
      path: '/api/public/sagacepay-webhook'
      fullPath: '/api/public/sagacepay-webhook'
      preLoaderRoute: typeof ApiPublicSagacepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/settings': {
      id: '/api/public/settings'
      path: '/api/public/settings'
      fullPath: '/api/public/settings'
      preLoaderRoute: typeof ApiPublicSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upsell': {
      id: '/api/public/upsell'
      path: '/api/public/upsell'
      fullPath: '/api/public/upsell'
      preLoaderRoute: typeof ApiPublicUpsellRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageRoute: PageRoute,
  AdminRoute: AdminRoute,
  ApiPublicCardConfigRoute: ApiPublicCardConfigRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicCheckoutStepRoute: ApiPublicCheckoutStepRoute,
  ApiPublicEventRoute: ApiPublicEventRoute,
  ApiPublicHypercashWebhookRoute: ApiPublicHypercashWebhookRoute,
  ApiPublicMetaEventRoute: ApiPublicMetaEventRoute,
  ApiPublicOrderRoute: ApiPublicOrderRoute,
  ApiPublicPixWebhookRoute: ApiPublicPixWebhookRoute,
  ApiPublicRastreioRoute: ApiPublicRastreioRoute,
  ApiPublicSagacepayWebhookRoute: ApiPublicSagacepayWebhookRoute,
  ApiPublicSettingsRoute: ApiPublicSettingsRoute,
  ApiPublicUpsellRoute: ApiPublicUpsellRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
